### ISSUE TITLE
ALG do not brake when beeing retracted

### ISSUE THREAD

**Issue by docmop** [shadowmage45/KSPWheel#12]
I don't know if this is only a sound bug or not.

Reproduction steps:

1. Plane with ALG
2. Move plane -> ALG's play moving sound
3. Take off
4. Retract ALG -> Sound still plays as if wheels are still moving

The stop the sound from playing you need to redeploy the gears, then brake.

**Comment by shadowmage45** [comment]
Thanks for the report and repo steps.

Yeah, still a bit of cleanup to do on the ALG parts.  This one is actually fairly easy, I merely need to clear the wheel rotation/velocity when retracting the wheels, and/or make the sounds module aware of the wheel state.

Should have this fixed up in the next release.

**Comment by shadowmage45** [comment]
Fixed in dev code.  Will be available with the next release.
