### ISSUE TITLE
Add brake input to tank steering at higher RPM.

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/KSPWheel#27]
Use two configurable brake-input curves for tank steering.
* Inverse proportional to torque output on the 'reverse' wheel.
* Full time, full-brake on the 'reverse' wheel.

How to tell what is the reverse wheel?

Even bigger problem -- where to put the code?
It needs access to the input state and calculations in motor module update code.
It also needs access to the input state and calculations in brake module update code.
It cannot logically be a part of either module, but needs to be part of both -.-
Make it a third module that can reference the first two? (won't work, needs to be part of the motor input calculations to know what direction is 'fwd')
Make it a part of motor module and use max motor torque as max brake output for steering function?

Current potential solution appears to be to link the feature into the motor module (so that it has access to the tank-steering input setup, which is needed to determine fwd-vs-rev direction), use the inverse output from the motor torque curve, and use the max motor torque and current-vs-max-rpm-percent to determine the 'brake-steering' torque.

**Comment by KerbalFoundries** [comment]
Look at the original KF code ;) no need to reinvent the wheel
