### ISSUE TITLE
ALG - Lack Drag Cube Updating

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/KSPWheel#28]
Need to hook into deployment states and re-render drag cubes when states are updated.  Possibly re-render at 2-3 points between retracted and deployed.

A full and robust solution (only usable in flight scene) would be to render one cube for each of deployed and retracted states and lerp between them, however as the entire model is driven through constraints this will not work (unless the constraint module is linked into the ALG module and force-updated between setting of deployment states).

Either way it will conflict with the base-modules handling of part scale, which manually rescales whatever drag cubes are present on the part.  This rescaling might be setup to enable/disable through a config field

**Comment by shadowmage45** [comment]
Attempting to fix this by:
* Adding a config field in base module that disables the drag cube updating from part scale.
* Adding in an animation-time based procedural drag-cube updating to the ALG.
* Delay updating until FlightIntegrator.firstFrame == true -- this ensures that the vessel is loaded and ready for physics (I think...).  At least this ensures that the drag-cube won't be overridden by the stock 'root part drag-cube reset' crap that has plagued SSTU drag-cube updating.
* In ALG module startup, set base module to disable drag-cube updates (removes need to adjust configs for these parts)

Should be fixed in dev versions, will do testing when next I can.

**Comment by rasta013** [comment]
Comments added on KF tracking thread...

**Comment by shadowmage45** [comment]
So, it is technically fixed in dev version.  The drag cube is properly re-rendered, and the drag cube values look to be updated appropriately.

Strangely, the drag is only reduced <25% when the wheels are retracted.

Potential causes may include (mostly guesses / things to investigate)
* Bump stop collider / temp colliders seen as 'dangling' even in retracted state, causing drag cube to be bigger than it should
  * Doesn't appear to be likely as the drag cube face values decrease appropriately for the change in size of the part.
   * Even if bump-stop collider is removed from the model prior to drag-cube rendering, it does not improve the situation.  Could still be other colliders, but as they are parented into the model they should not be causing danging collider problems.
* Strangely the drag, during retracting, goes from (for example) 40 -> 12 -> 30 -- at some point in the retract animation it renders with very little drag, but the drag comes back as the animation continues.
  * How do the drag cubes handle the model in its current configuration -- are the constraints being respected.
* Wrong drag-cube faces being used -- is it somehow using the Y+ face, when it should be using the X+ face?
* Is the 'extended' drag cube being rendered too conservatively? This might explain the discrepancies if the base drag cube was not as draggy as it should be.
  * However, from posts on the forum, this is not the case and the default extended is quite a bit draggier than the stock wheels.
  * Could be caused by there not being any colliders at all in the lower portion of the wheel meshes -- do drag cubes work on meshes, colliders, or both?

Things to investigate:
* ~~Is there a way for the drag-cube to output a graphic version of whatever it has rendered? -- would greatly help in debugging strange collider or mesh issues.  (possibly doable, with some reflection hackery)~~ doesn't appear to work, at all...
* Do drag cubes work on meshes, colliders, or both?
* There is a 'Drag_Hidden' tag that can be applied to parts (in addition to the wheel-collider/ignore layer setup)
  * Is there something on the part that needs to be removed from drag calculations
* Can manually specified 'override' drag cubes be built into the part config, and scaled as-per normal from the base module scaling.  Two cubes, one for each deployed and retracted.
  * Last I tried, override drag cubes did not setup the names properly, resulting in them being unusable by standard drag-cube switching setups.
* Can the part be set to procedural, and does the stock procedural drag-cube updating code handle things better?
* Are the particle emitters causing problems?  Stock code removes 'ParticleRenderer' and the new 'ParticleSystem', but does not appear to touch the old 'ParticleEmitter' setups (used by dust-fx)....
  * This could be easily tested by removing the dust-effects module from the part configs and seeing if the drag situation improves.

**Comment by shadowmage45** [comment]
There is something very screwey going on with the drag-cube rendering for these parts, that I have no clue what the origin of it is.

Here is the drag cube data from fully extended, and then fully retracted.  Fully extended looks about right for the face and extent values.  Fully retracted is all screwed up -- even though the bounds and face values are much lower than the extended cube, the drag for each face is often higher?  What gives?

(values are - area, drag, depth)
![image](https://cloud.githubusercontent.com/assets/1503399/23325721/c188cfee-fab4-11e6-9d10-0dcfd919b41a.png)

Not really sure what is up with that data, and I don't think it is anything that I can control or fix.  Likely 'solutions' will be to hack around it with manually specified drag cubes in the part configs and manually lerping between them, while allowing the base module to scale the part with scale.

**Comment by shadowmage45** [comment]
For now, I have copied the drag cubes out of the stock 'medium' landing gear, and lerp between them during gear retract/deploy animation.

![image](https://cloud.githubusercontent.com/assets/1503399/23326486/5006f1be-fabb-11e6-8aa0-0d3b8b3b2e7f.png)

Will attempt to refine the drag-cubes a bit more and go with this setup/system until I can find out the cause of the improper drag cube rendering.
