### ISSUE TITLE
EC consumption at VAB

### ISSUE THREAD

**Issue by yalov** [shadowmage45/KSPWheel#49]
1.  EC consumption for wheels not shows up at VAB module section (or stat section) and units would be helpful.   
So
    - max speed: 65
    - max load: 4

    changes to
    - max EC: xx/s
    - max load: 4 t
    - max speed: 65 m/s

2. EC not shows up at right-click menu.
3. C = 2πr, but `×2 TweakScale` → `×2 Speed` look like overpower. Not sure.

**Comment by shadowmage45** [comment]
Will take a look at adding in the max default EC consumption to the standard part info, and the current-max-ec consumption for current settings to the PAW.

Hopefully I kept track of my backwards-calculation set (the math behind the EC calc is... complex.. to say the least).
