### ISSUE TITLE
Supporting for 1.2.* version?

### ISSUE THREAD

**Issue by byaka** [shadowmage45/KSPWheel#50]
Unfortenly KSP 1.3 not ready yet for RSS+RO, so i'm steal use 1.2 version.
But latest versions of your awesome mod craching my game on loading due 'localizator' class issue.
Any chance to solving this problem?

**Comment by blowfishpro** [comment]
You can always find older versions under the "Releases" tab from the repo homepage.  The first version for 1.3 says as much, so it should be relatively simple to identify which version you need.

**Comment by shadowmage45** [comment]
KSP 1.2 version -- https://github.com/shadowmage45/KSPWheel/releases/tag/0.9.4.15

No guarantees that it'll work with any of the mods that use it though, as they've likely adapted for whatever changes have been done in the interim.

**Comment by byaka** [comment]
Yep, i know. I mean, no plans of backporting new feautures?

**Comment by blowfishpro** [comment]
I'm going to take a wild guess and say that the answer is no.  Even mods associated with RO aren't really releasing new versions for 1.2.2 anymore, really just waiting for someone to give the whole ecosystem the push it needs to get to 1.3
