### ISSUE TITLE
Add User Controlled 'Extension' for deployable parts.

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/KSPWheel#51]
* User-driven constraint-type module
* Allows for user to set the 'deploy' extension (linear translation) or angle (rotation) of a specific transform in the suspension hierarchy.
* Intended to allow for user-configurable deploy-angle limits and/or landing-leg height.
* Needs to work along-side the 'locked suspension' setting on landing legs.
* Needs to hook into the deployment module, and move back towards the specified 'retracted' state whenever gear/legs are retracted.

### Features
* Config specified 'retracted-default' position. (vector3? float?)
  * Represents where the mesh sits when 'retracted'
  * Also needs a config value to denote when to start and end the retraction sequence relative to the retract animation.
* Config specified 'extended-default' position. (vector3? float?)
* Config specified 'movement axis' - constrained to move (or rotate) along that single axis
* Config specified 'max adjustment' - amount user can adjust away from the default
* Config specification if it is a linear translation, or a rotation.
  * For translation, the defaults are for the X,Y, or Z local position
  * For rotation, the defaults are for the X,Y, or Z local rotation.
* Single UI slider with a 0-1 input range (0-100%),

### Functions
* Rotate or position specified transform for the current deployment state (optional) and user-selected 'deployment amount'.

**Comment by RaccoonTOF** [comment]
Just a request that if/when this is implemented, it be a case of rotation AND/OR extension limits.  Some landing legs have both a rotation portion and an extension portion to their deployment, it would be nice to be able to set both independently.

**Comment by shadowmage45** [comment]
Pretty much exactly that.

A part can have multiple user-controlled animation modules.  Each module will be responsible for a single transform, and for either extension (position), or rotation.  You'll be able to configure each module separately for its limits, and the config will specify how these modules link together for UI control (i.e. how many 'deploy' buttons there are; each module will still have its own slider control regardless of how many deploy buttons there are).

**Comment by RaccoonTOF** [comment]
Very cool :)  I was just concerned by all the wording in the original commenting saying "or" and wasn't sure if that was an exclusive or inclusive "or" ;)

**Comment by shadowmage45** [comment]
Implemented in dev; see recent forum posts for examples.  Multiple modules can be added, each one adds a single GUI button, and each one can control multiple transforms.

Used in combination with constraints, many 'baked' animations could be eliminated from parts in favor of user configurable deployment setups.
