### ISSUE TITLE
Dust Effects - Broken in KSP 1.4

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/KSPWheel#55]
Due to KSP switching to shuriken particle system.

Unsure how viable this will be for a replacement, if it will even be usable.

**Comment by blowfishpro** [comment]
SmokeScreen transitioned a while back without much trouble it seems.  Might also be worth contacting sarbian for advice on this.

**Comment by shadowmage45** [comment]
From a brief look at the ParticleSystem API -- the conversion will be doable, but massively painful.  Basically going to be a complete rewrite of the DustEffects system, as precisely zero of the existing code can be used by the new system.

Also going to have to create my own particle textures, as I was previously using some SQUAD particle prefabs, which are obviously not going to work (or likely even exist) in the new versions).  Seems like a good opportunity to define a unique secondary effect to use for the water 'splash' stuff as well (or possibly multiple effects).

In the short-term I'm likely going to disable the existing dust-effects code entirely to resolve the current NRE issues reported on the forums, and push out an updated release with the dust disabled.

Will aim to have the rewritten system back in place 'in a few weeks'.  Sadly, I really do have more important things to fix in other mods (e.g. TU has some bad breakage, and SSTU is entirely broken at the moment).

**Comment by shadowmage45** [comment]
Wow.. the syntax for using the new particle system is absolutely atrocious.  Its like Unity actively hates their customers and wants them to die in a fire or something.

Every.... single.... property change has to be wrapped using an extra variable to pull out their asinine 'struct module' garbage.

What should be a simple 'set property to X'  
````particleSystem.emission.enabled = false````

Instead has to be implemented like so:
````
var emissionModule = particleSystem.emission;
emissionModule.enabled = false;
````

Now try doing that across a couple hundred lines of code that adjust particle properties.  Utter trash.  I hate Unity more every day....
