### ISSUE TITLE
Texture reference broken

### ISSUE THREAD

**Issue by brustmopf** [shadowmage45/KSPWheel#57]
Not that this is an issue in game, but the error log gets the following errors:

[ERR 23:45:49.304] Texture 'KerbalFoundries/Assets/RepulsorSurfaceDiffuse' not found!

[ERR 23:45:49.387] Texture 'KerbalFoundries/Assets/SurfaceTrackSurface' not found!

is it possible to clean the assets in  the next release ?

**Comment by shadowmage45** [comment]
Issue is part of KerbalFoundries, and does not belong in this repository.

Also, should be fixed as soon as the model/texture revamp is done.
