### ISSUE TITLE
BUG: May have problems with FAR

### ISSUE THREAD

**Issue by shadowmage45** [shadowmage45/KSPWheel#6]
Need to investigate FAR support...

**Comment by blowfishpro** [comment]
Has someone reported issues with FAR?  Handling of animation changes is built into FAR, and I don't see anything else here that I'm aware would affect voxelization.

**Comment by shadowmage45** [comment]
There were some mumblings during the pre-release testing regarding the FAR pre-release, where apparently far would just fail if KSPWheel was installed.  So, posted this here just in case.

However I'm of the same thought as you -- there really shouldn't be any conflicts between the two considering what they do.  At most I might need to add in support for calling the FAR update-geometry code bit on scale or animation changes.

**Comment by shadowmage45** [comment]
[ksp-far-log.txt](https://github.com/shadowmage45/KSPWheel/files/724630/ksp-far-log.txt)

Log file with FAR problems.

http://i.imgur.com/wUCQNmI.png

**Comment by AkiraR** [comment]
Here are some more logs and stuff, screenshots are on dropbox because for whatever reason I can't upload anything to imgur at the moment.

https://www.dropbox.com/sh/07oyi1h8mh7m1ph/AACd0z5YT1cUxF2CvJ-_cd4Ka?dl=0

EDIT: I started an issue on the FAR git as well, hope that isn't taboo or something I'm new to this git business
https://github.com/ferram4/Ferram-Aerospace-Research/issues/165

**Comment by shadowmage45** [comment]
Bit of information after some initial investigation:
* Wheel models themselves appear to be fine.  Removing all modules from the wheels allows them to voxelize properly.
* Problem is not specific to the 'bump-stop collider'.  Bump-stop collider is not even present in the editor where the voxelization issues first manifest.
* Attempts to activate voxelization viewing in the editor when the problem is occurring results in a null-ref here: https://github.com/ferram4/Ferram-Aerospace-Research/blob/KSP_update/FerramAerospaceResearch/FARAeroComponents/VehicleAerodynamics.cs#L350
* Further 'deep' investigation reveals that something in the OnStart method of KSPWheelBase is causing FAR voxelization to fail.  Commenting out the OnStart() code allows voxelization to work (but of course the wheel does not).

**Comment by shadowmage45** [comment]
More investigation;

The problem appears to be caused by setting the part.collider field to null during module initialization.  Which then causes problems with this line in FAR code: https://github.com/ferram4/Ferram-Aerospace-Research/blob/ea259af5989ee0826b18c346cc748741672c81f5/FerramAerospaceResearch/FARPartGeometry/GeometryPartModule.cs#L192

I have no idea why that field is being used to calculate anything in regards to FAR.  Its only use in stock is for explosion related collision handling (it has no reason to be used in any sort of aero calculations).

Further investigations reveal this may also be related to the removal of the bounds-collider and/or collision enhancer colliders.  If -either- the code to null the part.collider field -or- the code to remove colliders is run, voxelization fails.

**Comment by shadowmage45** [comment]
Have this tentatively fixed in dev code;  fix is in place but undergoing further testing.

May require additional work to handle the bump-stop colliders and adding them to the exclusions list that FAR has provided (they will need to start using consistent naming rather than using the name of the wheel/transform they are attached to).
