### ISSUE TITLE
KSPWheel version 0.13.10.29 can't be CKAN installed

### ISSUE THREAD

**Issue by Jacke4913** [shadowmage45/KSPWheel#62]
I just noticed that the latest version of KSPWheel couldn't be installed in CKAN.  Did a little digging and saw that was due to the CKAN metadata have a wrong value for the ksp_version_max:

> "version": "0.13.10.29",
> "ksp_version_min": "1.6.0",
> "ksp_version_max": "1.5.9", 

Raised it as an issue with CKAN:

https://github.com/KSP-CKAN/NetKAN/issues/6975

HebaruSan replied it was due to the URL value in the .version pointing to a .version with the incorrect info:

> That's from http://ksp-avc.cybutek.net/version.php?id=429 which is specified in the "URL" property of the .version file. Try reporting it to the mod author.

Passing this onto you.  Thanks!

**Comment by shadowmage45** [comment]
Thanks for the report, should be able to get this fixed up for the next release.  I'm hoping to be able to push out some updates 'soon', so likely within the next week or so.
