### ISSUE TITLE
Resource Use for Deployment/Retraction

### ISSUE THREAD

**Issue by svm420** [shadowmage45/KSPWheel#63]
Adding this as a request for a future enhancement.

**Comment by shadowmage45** [comment]
Perfect, thanks.  Makes sure it doesn't get forgotten about or lost in the forum churn.

As stated on the forums -- seems like a simple addition, and entirely optional, so nothing really standing in the way of adding it.  Should be able to get it in for the next release.  Will update this ticket with details on the progress/issues/config setup/etc

**Comment by shadowmage45** [comment]
Implemented in dev; will be available with the next release.

````
        [KSPField]
        public bool useResourceDeploy = false;

        [KSPField]
        public bool useResourceRetract = false;

        [KSPField]
        public float deployResourceCost = 0f;

        [KSPField]
        public float retractResourceCost = 0f;

        [KSPField]
        public string deployResourceName = string.Empty;

        [KSPField]
        public string retractResourceName = string.Empty;
````
