### ISSUE TITLE
.version file is bad

### ISSUE THREAD

**Issue by linuxgurugamer** [shadowmage45/KSPWheel#66]
The error:
-AVC -> Error: KSP_VERSION_MIN greater than KSP_VERSION_MAX

The obtained file:

`{
  "NAME": "KSPWheel",
  "URL": "http://ksp-avc.cybutek.net/version.php?id=429",
  "DOWNLOAD": "https://github.com/shadowmage45/KSPWheel/releases/tag/0.14.11.30",
  "CHANGE_LOG_URL": "https://github.com/shadowmage45/KSPWheel/releases/tag/0.14.11.30",
  "VERSION": {
    "MAJOR": 0,
    "MINOR": 14,
    "PATCH": 11,
    "BUILD": 30
  },
  "KSP_VERSION": {
    "MAJOR": 1,
    "MINOR": 6,
    "PATCH": 0
  },
  "KSP_VERSION_MIN": {
    "MAJOR": 1,
    "MINOR": 6,
    "PATCH": 0
  },
  "KSP_VERSION_MAX": {
    "MAJOR": 1,
    "MINOR": 5,
    "PATCH": 9
  }
}`

**Comment by shadowmage45** [comment]
Strange, thought I fixed that with the last releases?

**Comment by shadowmage45** [comment]
Indeed, the included .version file seems to be correct -- https://github.com/shadowmage45/KSPWheel/blob/master/GameData/KSPWheel/KSPWheel.version

Where is this error originating from?

**Comment by linuxgurugamer** [comment]
This is the .version file as it was just installed.  CKAN says 0.14.11.30, but the file says 0.14.12.31

I just downloaded the file from the Github Releases, and in that file it has the following:
`{
	"NAME":"KSPWheel",
	"URL":"http://ksp-avc.cybutek.net/version.php?id=429",
	"DOWNLOAD":"https://github.com/shadowmage45/KSPWheel/releases/tag/0.14.12.31",
	"CHANGE_LOG_URL":"https://github.com/shadowmage45/KSPWheel/releases/tag/0.14.12.31",
	"VERSION":
	{
		"MAJOR":0,
		"MINOR":14,
		"PATCH":12,
		"BUILD":31
	},
	"KSP_VERSION":
	{
		"MAJOR":1,
		"MINOR":6,
		"PATCH":1
	},
	"KSP_VERSION_MIN":
	{
		"MAJOR":1,
		"MINOR":6,
		"PATCH":0
	},
	"KSP_VERSION_MAX":
	{
		"MAJOR":1,
		"MINOR":6,
		"PATCH":9
	}
}
`

**Comment by shadowmage45** [comment]
Indeed there is some oddity with the version #'s.  Wonderful....

**Comment by shadowmage45** [comment]
Should be fixed.  Hopefully....  Please let me know if there are still issues and I can push a new release with an incremented version number.

Published a new release with the proper version number and tag.  Updated ksp-avc.cybutek.net with the same version info.  All source should now line up.

(really need to find an automated build system that doesn't take more effort to setup and learn than the programming language it is used for....)

**Comment by linuxgurugamer** [comment]
Sorry, I didn't realize you had done a full release.

There's something wrong on the CKAN side, for some reason it always say the KSP_VERSION_MAX is 1.5.9 instead of what's in the file which is 1.6.9

**Comment by linuxgurugamer** [comment]
I found the problem, it's the version numbers of your releases.

Apparently 15 days ago you did a release and the number is:   0.14.11.30
while the latest release is:  0.4.11.30

The mistake is in the latest release, it should be 0.14.11.30.  The good news is all you need to do is edit the tag of the latest release to be correct, and CKAN will pick it up in a few hours

**Comment by HebaruSan** [comment]
When in doubt about a KSP-AVC problem, check the URL property:

```json
	"URL":"http://ksp-avc.cybutek.net/version.php?id=429",
```

http://ksp-avc.cybutek.net/version.php?id=429 (excerpted):

```json
"KSP_VERSION_MIN":{"MAJOR":1,"MINOR":6,"PATCH":0},
"KSP_VERSION_MAX":{"MAJOR":1,"MINOR":5,"PATCH":9}
```

**Comment by linuxgurugamer** [comment]
In this case, the issue is that CKAN is grabbing the wrong file because of a mistake in the releases page.
I've sent info via PM to him about it
