### ISSUE TITLE
KSPWheel Wheels Break Instantly On Craft Load

### ISSUE THREAD

**Issue by VaelophisNyx** [shadowmage45/KSPWheel#71]
As the title implies, all wheels reliant on this mod for their function simply become overstressed and break instantaneously on the launch-pad/runway.

if it helps: The wheels are on a rover atop a rocket, inside a stock faring. I have KJR installed, and the wheels are free-floating in the faring, nothing is touching them but that which they are attached to.
I checked the log and the only error I had was a null-ref for a contract; and the message about the wheels over-stressing.

**Comment by VaelophisNyx** [comment]
It appears to be the faring, actually. Once removed and reloaded, the wheels do not break?

**Comment by shadowmage45** [comment]
> It appears to be the faring, actually. Once removed and reloaded, the wheels do not break?

Good information to have.  Could be that the stock fairings have changed how they generate colliders/etc, and that the wheels are impacting with these colliders.  (KSPWheel does not ignore colliders they way the stock wheel module does, and so it will register collisions with -anything- that has a collider)

If that is indeed the case, it _might_ be possible to implement a solution, however it will not be fast nor simple, and will degrade performance when in use.

**Comment by VaelophisNyx** [comment]
In addition to this (sorry for the delay) the wheels also over-accelerate if st to gear ratios too high for them, and break near instantly. The on-load-break still occurs but if the wheels are locked and the faring is removed they're fine until unlocked and used.

**Comment by shadowmage45** [comment]
Apologies for the late response, have been away from the modding scene for a while.

KSPWheel does not filter what its wheels will 'impact' to remove same-vessel collisions.  Stock fairings, when they have colliders enabled, could very well be creating colliders in places where the wheels are impacting them.  

This quirk could very well be interacting with a bug in KSPWheel where I'm not calculating the local velocity properly when 'colliding' with another moving body on the same vessel, thinking that it is colliding at your orbital speed/surface speed, and thus instantly 'breaking'.

Of course, as soon as the fairings are jettisoned, there are no more collisions, and thus no more breakage.

The issue regarding gear-settings and over-speeding wheels is entirely unrelated to the collision induced wheel breakage; but I can confirm that this issue can be seen in specific configurations as well.  Need to do some better integration regarding the wheel rotational velocities.
